?eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.31.10:8761/eureka/
  instance:
    prefer-ip-address: true
    #instance-id: 192.168.31.13:spring-cloud-producer:9000
    ip-address: ${spring.cloud.client.ipAddress}
    instance-id:  ${spring.cloud.client.ipAddress}:${server.port}
    hostname: ${spring.cloud.client.ipAddress}

server:
  port: 8001
spring:
  application:
    name: spring-cloud-producer
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/trafficdata?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useUnicode=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
    #hikari连接池
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: select 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 20
      minimum-idle: 20
      #spring.datasource.max-idle=10
      ##指定连接池等待连接返回的最大等待时间，毫秒单位.
      #spring.datasource.max-wait=10000
      ##指定必须保持连接的最小值
      #spring.datasource.min-idle=5
      ##指定连接池中最大的活跃连接数.
      #spring.datasource.secondary.max-active=50
      #spring.datasource.initial-size=5
      #spring.datasource.validation-query=SELECT 1
      #spring.datasource.test-on-borrow=false
      #spring.datasource.test-while-idle=true
      #spring.datasource.time-between-eviction-runs-millis=18800
      #spring.datasource.jdbc-interceptors=ConnectionState;SlowQueryReport(threshold=0)
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AndyYHL/web3j.git
          search-paths: config-repo
          username: caozhiqiang@hashsico.com
          password: Admin12345
    inetutils:
      preferred-networks:
  thymeleaf:
    prefix: classpath:/templates/

mybatis:
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/*/*.xml

