server:
  port: 8001   #配置端口
?eureka:
  client:
    register-with-eureka: false   #是否向服务端注册自己，它本身就是Eureka Server，所以为false
    fetch-registry: false         #表示是否从Eureka Server获取信息，因为这是一个单节点，不需要同步其它Eureka Server的数据，所以为 false
    serviceUrl:
      #defaultZone: http://192.168.31.10:8761/eureka/ #设置 Eureka Client 与 Eureka Server 同步的地址，注册、查询服务都要使用该地址，多个地址可用逗号分隔
  instance:
    prefer-ip-address: true   #是否需要像服务器发送IP地址
    #instance-id: 192.168.31.13:spring-cloud-producer:9000
    ip-address: ${spring.cloud.client.ipAddress}
    instance-id:  ${spring.cloud.client.ipAddress}:${server.port}
    hostname: ${spring.cloud.client.ipAddress}
spring:
  application:
    name: spring-cloud-producer
  sleuth:
     enabled: false
  #加入JSP支持
  mvc:
    view:
      suffix: .jsp
      prefix: /view
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.104.55.109:3306/block?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useUnicode=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
    #hikari连接池
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: select 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 20
      minimum-idle: 20
      #spring.datasource.max-idle=10
      ##指定连接池等待连接返回的最大等待时间，毫秒单位.
      #spring.datasource.max-wait=10000
      ##指定必须保持连接的最小值
      #spring.datasource.min-idle=5
      ##指定连接池中最大的活跃连接数.
      #spring.datasource.secondary.max-active=50
      #spring.datasource.initial-size=5
      #spring.datasource.validation-query=SELECT 1
      #spring.datasource.test-on-borrow=false
      #spring.datasource.test-while-idle=true
      #spring.datasource.time-between-eviction-runs-millis=18800
      #spring.datasource.jdbc-interceptors=ConnectionState;SlowQueryReport(threshold=0)
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AndyYHL/web3j.git
          search-paths: config-repo
          username: caozhiqiang@hashsico.com
          password: Admin12345
    #多网卡配置
    inetutils:
      preferred-networks:
  thymeleaf:
    prefix: classpath:/templates/
 #网页编码设置
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
mybatis:
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/*/*.xml
#日志配置
logging:
  config: classpath:log4j2.xml